# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-SASL-Authd
version:      0.01
version_from: lib/Authen/SASL/Authd.pm
installdirs:  site
requires:
    IO:                            1.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
